### PR TITLE
Redirect to base CLM if list item is not found

### LINKED ISSUE #145: CLM should redirect to base url if list/item is not found
If you visit http://localhost:8000/plugins/controlled-list-manager/list/uuid or http://localhost:8000/plugins/controlled-list-manager/item/uuid and that list or item are not present in the db, the whole CLM fails to load. Instead we should redirect to http://localhost:8000/plugins/controlled-list-manager

### PR DESCRIPTION
**Pull request by johnatawnclementawn**
Resolves #145

### CODE REVIEW

File: arches_controlled_lists/src/arches_controlled_lists/components/tree/ListTree.vue [hunk 1]
```diff
@@ -93,25 +99,38 @@ const navigate = (newRoute: RouteLocationNormalizedLoadedGeneric) => {
...
+                        ...Object.fromEntries(
+                            [
+                                found.data.controlled_list_id,
+                                ...itemsToExpandIds,
+                            ].map((x) => [x, true]),
+                        ),
+                    };
+                    selectedKeys.value = { [found.data.id]: true };
+                }
+            } catch (error) {
```
Comment (johnatawnclementawn) [inline arches_controlled_lists/src/arches_controlled_lists/components/tree/ListTree.vue:124]: Should we show toast to alert user that the URL they navigated to did not result in an item hit?

Comment (robgaston) [reply arches_controlled_lists/src/arches_controlled_lists/components/tree/ListTree.vue:124]: I think so 👍

**Review by robgaston — APPROVED** [review]
lgtm
